spring:
  application:
    name: pet-store
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pet_store?useSSL=false&serverTimezone=Asia/Shanghai
    username: 
    password: 
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  ai:
    deepseek:
      api-key: 
      base-url: 
      chat:
        model: 
        temperature: 
        timeout: 

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

knife4j:
  enable: true
  setting:
    language: zh_cn
