<template>
  <div class="admin-page">
    <div class="page-header"><h2>商品监管</h2><p>查看平台商品并处理需要强制下架的内容</p></div>
    <div class="search-bar"><input v-model="keyword" placeholder="搜索商品名称" @keyup.enter="search" /><input v-model="storeFilter" placeholder="按门店ID筛选" /><select v-model.number="statusFilter"><option :value="-1">全部状态</option><option :value="1">上架</option><option :value="0">下架</option><option :value="2">已售出</option></select><button class="btn btn-primary" @click="search">搜索</button><button class="btn btn-outline" @click="reset">重置</button></div>
    <div class="table-wrap"><table class="data-table"><thead><tr><th>商品</th><th>门店</th><th>价格</th><th>库存</th><th>状态</th><th>平台限制</th><th>监管操作</th></tr></thead><tbody>
      <tr v-for="item in records" :key="item.id"><td>{{ item.productName||item.name }}</td><td>{{ item.store?.storeName||item.storeId }}</td><td>¥{{ item.price }}</td><td>{{ item.stock }}</td><td><span class="badge" :class="statusBadge(productStatusCode(item.status,item.statusCode))">{{ productStatusLabel(item.status,item.statusCode) }}</span></td><td>{{ item.platformRestricted ? (item.offlineReason||'是') : '无' }}</td><td class="actions"><button class="btn btn-outline btn-sm" @click="showDetail(item.id)">详情</button><button v-if="productStatusCode(item.status,item.statusCode)===1" class="btn btn-danger btn-sm" @click="forceOff(item)">强制下架</button><button v-if="item.platformRestricted" class="btn btn-success btn-sm" @click="release(item)">解除限制</button></td></tr>
      <tr v-if="!loading&&!records.length"><td colspan="7" class="empty-row">暂无商品</td></tr><tr v-if="loading"><td colspan="7" class="empty-row">加载中...</td></tr>
    </tbody></table><div class="pagination" v-if="total"><button :disabled="page<=1" @click="go(page-1)">上一页</button><span>第 {{ page }} / {{ totalPages }} 页，共 {{ total }} 条</span><button :disabled="page>=totalPages" @click="go(page+1)">下一页</button></div></div>
    <div v-if="detail" class="modal-overlay" @click.self="detail=null"><div class="modal-card"><div class="modal-header"><h3>商品详情</h3><button class="modal-close" @click="detail=null">✕</button></div><div class="detail-list"><p><b>商品：</b>{{ detail.productName||detail.name }}</p><p><b>门店：</b>{{ detail.store?.storeName||detail.storeId }}</p><p><b>价格：</b>¥{{ detail.price }}</p><p><b>库存：</b>{{ detail.stock }}</p><p><b>状态：</b>{{ productStatusLabel(detail.status,detail.statusCode) }}</p><p><b>平台限制：</b>{{ detail.platformRestricted?'是':'否' }}</p><p><b>下架原因：</b>{{ detail.offlineReason||'-' }}</p><p><b>下架时间：</b>{{ detail.offlineTime||'-' }}</p><p><b>操作人员：</b>{{ detail.offlineUserId||'-' }}</p><p><b>描述：</b>{{ detail.productDesc||detail.detail||'-' }}</p></div></div></div>
  </div>
</template>

<script setup lang="ts">
import { computed,onMounted,ref } from "vue";import { forceOfflineProduct,getAuditorProduct,listAuditorProducts,releaseOfflineProduct } from "../../api/auditorProduct";import type { Product } from "../../types/product";import { productStatusCode,productStatusLabel,statusBadge } from "../../utils/status";import { notify } from "../../utils/notify"
const records=ref<Product[]>([]),detail=ref<Product|null>(null),total=ref(0),page=ref(1),keyword=ref(""),storeFilter=ref(""),statusFilter=ref(-1),loading=ref(false);const size=10;const totalPages=computed(()=>Math.max(1,Math.ceil(total.value/size)))
async function fetchData(){loading.value=true;try{const result=await listAuditorProducts({page:page.value,size,keyword:keyword.value||undefined,storeId:storeFilter.value||undefined,status:statusFilter.value>=0?statusFilter.value:undefined});records.value=result.records;total.value=result.total}finally{loading.value=false}}
function search(){page.value=1;fetchData()}function reset(){keyword.value="";storeFilter.value="";statusFilter.value=-1;search()}function go(next:number){page.value=next;fetchData()}async function showDetail(id:string){detail.value=await getAuditorProduct(id)}
async function forceOff(item:Product){if(!confirm(`确定强制下架「${item.productName||item.name}」？`))return;const input=prompt("请输入强制下架原因（必填）：");if(input===null)return;const reason=input.trim();if(!reason){notify("强制下架原因不能为空","error");return}await forceOfflineProduct(item.id,reason);notify("强制下架成功");await fetchData()}
async function release(item:Product){if(!confirm(`确定解除「${item.productName||item.name}」的平台限制？商品将保持下架。`))return;await releaseOfflineProduct(item.id);notify("平台限制已解除，商品仍保持下架");await fetchData()}
onMounted(fetchData)
</script>
<style scoped>.detail-list{display:grid;gap:12px;color:var(--text2)}.detail-list b{color:var(--text1)}</style>
